### ISSUE TITLE
Создание контроллера работы с пользователем

### ISSUE THREAD

**Issue by MedAlexey** [technopolis-android-2020/server#3]
**Название класса:** User

**Расположение:**  src/main/java/com/technopolis/server/controller/

**Обрабатываемые запросы**  (Их подробное описание находится в [wiki](https://github.com/technopolis-android-2020/server/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%BC)):

* Регистрация нового пользователя ( _.../registr_  ) ([подробнее](#a_reg))
* Обновление токенов пользователя ( _.../refresh_ ) ([подробнее](#a_refresh))
* Аутентификация пользователя ( _.../auth_ ) ([подробнее](#a_auth))

**Работу с БД нужно вынести в:** src/main/java/com/technopolis/server/database/

**Структура БД** описана в [wiki](https://github.com/technopolis-android-2020/server/wiki/%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0-%D0%91%D0%94).

-------

Ассоциативные массивы видов: "access token пользователя - таймаут токена" и "refresh token - access token" хранятся классе (_session.java_), располагающемуся в: _src/main/java/com/technopolis/server/session/_

------
<a name='a_reg'>**Регистрация нового пользователя:**</a>

1. Проверка наличия пользователя с таким логином (ответ с кодом 500 при наличии).
2. Занесение информации о пользователе в БД.
3. Генерация токенов.
4. Создание сессии пользователя (занесение информации о токенах и таймауте в ассоциативные массивы).
5. Ответ пользователю.

<a name='a_refresh'>**Обновление токенов:**</a>

1. Замена пары "refresh token - access token" в соответствующем ассоциативном массиве.
2. Замена пары "access token - timeout" в сответствующем ассоциативном массиве.
3. Замена refresh токена соответствующего пользователя в БД.
4. Ответ пользователю

<a name='a_auth'>**Аутентификация пользователя:**</a>
1. Генерация новых токенов для соответствующего пользователя.
2. Замена текущих токенов пользователя (при наличии) на новые.
3. Ответ пользователю.

**Comment by nik27090** [comment]
API:
GET /api/v1/users/{id} : заголовок Authorization, токен Bearer_<token>.
	
POST /api/v1/auth/register : JSON username, firstName, lastName, email, password.
	вернет refreshToken, username.
POST /api/v1/auth/login : JSON username, password.
	вернет username, accessToken, refreshToken.
POST /api/v1/auth/refresh : JSON username, refreshToken.
	вернет username, accessToken.
